# Generated by Django 2.2 on 2019-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movieTitle', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=100)),
                ('download', models.URLField()),
                ('musicDirector', models.CharField(max_length=100)),
            ],
        ),
    ]
