# Generated by Django 2.2 on 2019-04-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.CharField(max_length=6, unique=True)),
                ('drivername', models.CharField(max_length=20)),
                ('driverno', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('identitycard', models.CharField(max_length=8)),
            ],
        ),
    ]
